#pragma once
enum class TokenType {
    // Single character
    LEFT_PAREN, RIGHT_PAREN, LEFT_BRACE, RIGHT_BRACE, LEFT_SQUIGGLE, RIGHT_SQUIGGLE, COMMA, COLON, DOT, MINUS, MINUS_MINUS, PLUS, PLUS_PLUS,
    SEMICOLON, SLASH, STAR, PERCENT, PLUS_EQUAL, MINUS_EQUAL, SLASH_EQUAL, STAR_EQUAL, PERCENT_EQUAL,

    // One or two character
    NOT, NOT_EQUAL,
    EQUAL, EQUAL_EQUAL,
    GREATER, GREATER_EQUAL,
    LESS, LESS_EQUAL,

    // Literals
    IDENTIFIER, STRING, NUMBER,

    // Keywords
    AND, CLASS, DEF, ELSE, FALSE, FOR, IF, IN, INPUT, NONE, OR, PRINT, RETURN, SUPER, THIS, TRUE, WHILE,

    // Indents and newlines
    INDENT, DEDENT, NEWLINE,

    FSTRING_EXPR,

    EOF_
};
